# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYZYZYJlC-Dvkc9pf9BwOEUsC3UtR9gf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)

time = np.arange(0, 1000)

temperature = 50 + 0.02*time + np.random.normal(0, 1, 1000)
vibration = 5 + 0.01*time + np.random.normal(0, 0.5, 1000)
pressure = 100 + 0.03*time + np.random.normal(0, 2, 1000)
acoustic = 60 + 0.015*time + np.random.normal(0, 1, 1000)

data = pd.DataFrame({
    'time': time,
    'temperature': temperature,
    'vibration': vibration,
    'pressure': pressure,
    'acoustic': acoustic
})

data.head()

from sklearn.ensemble import IsolationForest

model_if = IsolationForest(contamination=0.02)
data['anomaly'] = model_if.fit_predict(data[['temperature','vibration','pressure','acoustic']])

plt.scatter(data['time'], data['temperature'], c=data['anomaly'])
plt.title("Anomaly Detection")
plt.show()

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data[['temperature','vibration','pressure','acoustic']])

X = []
y = []

sequence_length = 20

for i in range(len(scaled_data)-sequence_length):
    X.append(scaled_data[i:i+sequence_length])
    y.append(scaled_data[i+sequence_length][0])

X = np.array(X)
y = np.array(y)

model = Sequential()
model.add(LSTM(50, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

model.fit(X, y, epochs=10, batch_size=32)

failure_threshold = 80

predictions = model.predict(X)

rul = (failure_threshold - predictions.flatten()) / 0.02

plt.plot(rul)
plt.title("Estimated Remaining Useful Life")
plt.show()

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y, predictions)
print("MSE:", mse)

pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# 
# st.title("AI Predictive Maintenance - Launch Pad Systems")
# 
# time = np.arange(0, 1000)
# temperature = 50 + 0.02*time + np.random.normal(0, 1, 1000)
# 
# data = pd.DataFrame({
#     'time': time,
#     'temperature': temperature
# })
# 
# st.line_chart(data.set_index('time'))

!pip install pyngrok

!pip install pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("3AFzGmFdTHc85ZlgpSRvKxGZmjd_Fq9pufZW4TAaYcDvJkb9")

public_url = ngrok.connect(8501)
print("Public URL:", public_url)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(42)

n_samples = 10000
time = np.arange(n_samples)

temperature = 70 + 0.01*time + np.random.normal(0, 2, n_samples)
vibration = 40 + 0.005*time + np.random.normal(0, 1.5, n_samples)
pressure = 25 + 0.008*time + np.random.normal(0, 1, n_samples)

# Simulate degradation trend
degradation = 0.0005 * time
RUL = 1000 - degradation*time
RUL[RUL < 0] = 0

data = pd.DataFrame({
    "time": time,
    "temperature": temperature,
    "vibration": vibration,
    "pressure": pressure,
    "RUL": RUL
})

data.to_csv("launchpad_sensor_data.csv", index=False)
data.head()

from sklearn.ensemble import IsolationForest

features = data[["temperature", "vibration", "pressure"]]

iso = IsolationForest(contamination=0.02)
data["anomaly"] = iso.fit_predict(features)

data["anomaly"] = data["anomaly"].map({1:0, -1:1})

print("Anomalies Detected:", data["anomaly"].sum())

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(features)

X = []
y = []

window = 20

for i in range(len(scaled_features)-window):
    X.append(scaled_features[i:i+window])
    y.append(data["RUL"].iloc[i+window])

X, y = np.array(X), np.array(y)

model = Sequential()
model.add(LSTM(50, return_sequences=True, input_shape=(window, 3)))
model.add(LSTM(50))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')

model.fit(X, y, epochs=5, batch_size=64)

model.save("lstm_rul_model.h5")

import streamlit as st
import numpy as np
import joblib
from tensorflow.keras.models import load_model

st.title("AI-Based Predictive Maintenance for Launch Pad Systems")

model = load_model("lstm_rul_model.h5")

temperature = st.slider("Temperature", 0, 200, 70)
vibration = st.slider("Vibration", 0, 100, 40)
pressure = st.slider("Pressure", 0, 100, 25)

input_data = np.array([[temperature, vibration, pressure]])
input_data = input_data.reshape((1,1,3))

if st.button("Predict"):
    predicted_rul = model.predict(input_data)[0][0]

    if predicted_rul < 200:
        st.error(f"⚠ Critical Warning! Estimated RUL: {predicted_rul:.2f} hours")
    else:
        st.success(f"Machine Operating Normally. Estimated RUL: {predicted_rul:.2f} hours")

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.losses import MeanSquaredError

# Generate dummy dataset
np.random.seed(42)
n_samples = 3000
time = np.arange(n_samples)

temperature = 70 + 0.01*time + np.random.normal(0,2,n_samples)
vibration = 40 + 0.005*time + np.random.normal(0,1.5,n_samples)
pressure = 25 + 0.008*time + np.random.normal(0,1,n_samples)

RUL = 1000 - 0.05*time
RUL[RUL < 0] = 0

data = pd.DataFrame({
    "temperature": temperature,
    "vibration": vibration,
    "pressure": pressure,
    "RUL": RUL
})

# Scaling
scaler = MinMaxScaler()
features = scaler.fit_transform(data[["temperature","vibration","pressure"]])

X, y = [], []
window = 10

for i in range(len(features)-window):
    X.append(features[i:i+window])
    y.append(data["RUL"].iloc[i+window])

X, y = np.array(X), np.array(y)

# Build model
model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(window,3)),
    LSTM(32),
    Dense(1)
])

# IMPORTANT FIX HERE 👇
model.compile(
    optimizer='adam',
    loss=MeanSquaredError()
)

model.fit(X, y, epochs=5, batch_size=32)

# SAVE IN NEW FORMAT (IMPORTANT)
model.save("lstm_rul_model.keras")

print("Model Saved Successfully!")

import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler

st.title("AI-Based Predictive Maintenance for Launch Pad Systems")

# Load model safely
model = load_model("lstm_rul_model.keras", compile=False)

temperature = st.slider("Temperature", 0, 200, 70)
vibration = st.slider("Vibration", 0, 100, 40)
pressure = st.slider("Pressure", 0, 100, 25)

if st.button("Predict"):

    # Create fake time window (repeat same input 10 times)
    input_data = np.array([[temperature, vibration, pressure]] * 10)
    input_data = input_data.reshape((1,10,3))

    predicted_rul = model.predict(input_data)[0][0]

    if predicted_rul < 200:
        st.error(f"⚠ Critical Warning! Estimated RUL: {predicted_rul:.2f} hours")
    else:
        st.success(f"Machine Operating Normally. Estimated RUL: {predicted_rul:.2f} hours")

!pip install pyngrok streamlit --quiet

from pyngrok import ngrok

ngrok.set_auth_token("3AFzGmFdTHc85ZlgpSRvKxGZmjd_Fq9pufZW4TAaYcDvJkb9")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# from tensorflow.keras.models import load_model
# 
# st.title("AI-Based Predictive Maintenance for Launch Pad Systems")
# 
# model = load_model("lstm_rul_model.keras", compile=False)
# 
# temperature = st.slider("Temperature", 0, 200, 70)
# vibration = st.slider("Vibration", 0, 100, 40)
# pressure = st.slider("Pressure", 0, 100, 25)
# 
# if st.button("Predict"):
# 
#     input_data = np.array([[temperature, vibration, pressure]] * 10)
#     input_data = input_data.reshape((1,10,3))
# 
#     predicted_rul = model.predict(input_data)[0][0]
# 
#     if predicted_rul < 200:
#         st.error(f"⚠ Critical Warning! Estimated RUL: {predicted_rul:.2f} hours")
#     else:
#         st.success(f"Machine Operating Normally. Estimated RUL: {predicted_rul:.2f} hours")

import subprocess

subprocess.Popen(["streamlit", "run", "app.py"])

public_url = ngrok.connect(8501)
print("Public URL:", public_url)

!ps aux | grep streamlit

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

predictions = model.predict(X)
mae = mean_absolute_error(y, predictions)
rmse = np.sqrt(mean_squared_error(y, predictions))

print("MAE:", mae)
print("RMSE:", rmse)